ALTER TABLE public.submissions
  ADD COLUMN IF NOT EXISTS highlight_package_id uuid REFERENCES public.highlight_packages(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS highlight_starts_at timestamptz,
  ADD COLUMN IF NOT EXISTS highlight_until timestamptz,
  ADD COLUMN IF NOT EXISTS highlight_hidden boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS submissions_highlight_idx
  ON public.submissions (highlight_until)
  WHERE is_highlight = true;

CREATE OR REPLACE VIEW public.public_submissions AS
SELECT id,
    user_id,
    company_name,
    event_title,
    date,
    start_time,
    end_time,
    location,
    description,
    video_link,
    category,
    created_at,
    address_street,
    address_number,
    address_neighborhood,
    address_city,
    address_state,
    address_zip,
    promotion_type,
    target_audience,
    promotion_rules,
    additional_details,
    status,
    sale_price,
    maintenance_cost,
    subscription_info,
    commission,
    stage,
    concept_description,
    deleted_at,
    rejection_reason,
    predicted_duration,
    atrativo_name,
    atrativo_type,
    atrativo_style,
    location_type,
    legal_acceptance,
    legal_acceptance_date,
    is_highlight,
    views_count,
    shares_count,
    image_url,
    latitude,
    longitude,
    age_rating,
    is_suitable_for_minors,
    report_count,
    moderation_status,
    artist_id,
    ai_moderation_score,
    ai_moderation_labels,
    image_url_story,
    image_url_whatsapp,
    slug,
    short_copy,
    long_copy,
    approved_at,
    approved_by,
    published_at,
    fotos,
    duvidas_source,
    COALESCE(responsavel_duvidas_whatsapp,
        CASE duvidas_source
            WHEN 'atrativo'::text THEN atrativo_contact
            WHEN 'estabelecimento'::text THEN location_contact
            ELSE phone
        END) AS duvidas_phone,
    responsavel_duvidas_whatsapp,
    highlight_until,
    highlight_hidden,
    (is_highlight AND NOT highlight_hidden AND (highlight_until IS NULL OR highlight_until > now())) AS highlight_active
   FROM submissions
  WHERE deleted_at IS NULL AND (status = ANY (ARRAY['aprovado'::text, 'publicado'::text, 'divulgado'::text]));